vn.trader/ibGateway/ibGateway.py, vn.trader/vtFunction.py, vn.trader/vtMain.py
1. 修复IB报错 2. 修复在MAC上编码错误, 默认设置位UTF8 3. 设置底部任务栏图标只在windows显示
=> 1. 修复IB报错 2. 修复在MAC上编码错误, 默认设置位UTF8 3. 设置底部任务栏图标只在windows显示

vn.trader/vtEngine.py
修复在MongoDB服务端异常情况下，启动vnpy依然显示MongoDB连接成功bug。
修改‘serverSelectionTimeoutMS’为3s(默认30s), 利用server_info()函数测试服务器是否正常。
=> 修复MongoDB连接bug

README.md
websocket虽然提供了相同的namespace，去掉了启动时时的错误，但真正能够连接okcoin的是websocket-client
=> websocket-client才是真正支持OKCoin的库

vn.trader/okcoinGateway/okcoinGateway.py
从okcoin获得深度行情数据中，原始版本对ask的处理有误，ask数据也是从高到低的,所以访问次序应该与bid相反.
=> 修复OKCoin行情中ask数据异常

.gitignore, vn.trader/ctaAlgo/strategyAtrRsi.py, vn.trader/uiBasicWidget.py
原版demo策略strategyAtrRsi中，在onBar后更新仓位变量pos，这样会导致仓位变动后直到下根bar生成才更新GUI的仓位变量。
修改为在onTrade中更新GUI。
=> 修正GUI中仓位变量pos不能实时更新的问题

vn.trader/riskManager/RM_setting.json, vn.trader/riskManager/rmEngine.py, vn.trader/riskManager/uiRmWidget.py, vn.trader/vtConstant.py, vn.trader/vtEngine.py
交易所规定，单品种单日保持不该超过500次。所以增加了这个功能。
原理是监听order变化，根据order状态判断次数。
如果是STATUS_NOTTRADED, STATUS_PARTTRADED, STATUS_ALLTRADED, STATUS_UNKNOWN这其中之一，增加一次，如果是STATUS_CANCELLED，增加两次。
超过指定次数的时候，发单不予通过。
另外，对于风控失败，增加了失败原因的枚举，以便对原因进行监控。
=> 风控模块增加单品种报撤单次数限制

vn.trader/ctaStrategy/ctaBacktesting.py
=> 解决回测时设置结束时间后缺失最后一天数据的Bug

vnpy/trader/gateway/lhangGateway/lhangGateway.py
针对数据记录、Cta引擎等需要order\tick\error等对象时间字符串中毫秒部分来格式化时间，否则会出现异常。
此pr修复这个问题。
=> 补齐链行返回框架对象的时间毫秒部分

vnpy/data/shcifco/vnshcifco.py
#432 
中期已在数据接口hisbar的返回值中增加了自然日字段
=> shcifco data api: use natural day instead of trading day

vnpy/trader/app/ctaStrategy/ctaEngine.py, vnpy/trader/vtEngine.py
1. ctaEngine.py saveSyncData中的content不是unicode字符串，和上下文不一致，而且在ubuntu上会有兼容问题
2. vtEngine.py 里面的单例模式，实测下来无效，初始化几次，打印日志时同一条信息就打印几条，已经改为新的单例模式，已经经过实盘测试，可用。
Close #
=>  vtEngine.py中LogEngine单例模式变更， ctaEngine.py中saveSyncData函数中字符串格式变更

vnpy/rpc/testClient.py, vnpy/rpc/testServer.py, vnpy/rpc/vnrpc.py
Step 3 of #818
1. $ pip install flake8 future # http://python-future.org/futurize_cheatsheet.html
2. $ git checkout -b modernize-python2-code
3. $ python2 -m flake8 vnpy/rpc --count --select=E901,E999,F821,F822,F823 --show-source --statistics
4. $ futurize --stage1 -w vnpy/rpc
5. $ python3 -m flake8 vnpy/rpc --count --select=E901,E999,F821,F822,F823 --show-source --statistics
6. $ git commit -am "Modernize Python 2 code to get ready for Python 3"
7. $ git push --force origin modernize-python2-code
=> Modernize vnpy/rpc to get ready for Python 3

beta/api/korbit/vnkorbit.py
Part of step 2 of #818 -- Fixes one of three issues in:
$ __python2 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./beta/api/korbit/vnkorbit.py:76:13: F821 undefined name 'logging'
logging.error("exception: {}, response_text: {}".format(e, response.text))
^
./examples/VnTrader/run.py:54:23: F821 undefined name 'xtpGateway'
me.addGateway(xtpGateway)
^
./vnpy/trader/gateway/lbankGateway/__init__.py:6:16: F821 undefined name 'lbankGateway'
gatewayClass = lbankGateway
^
3     F821 undefined name 'logging'
3
```
=> import logging in vnkorbit.py

examples/VnTrader/run.py
Part of step 2 of #818 -- Fixes one of three issues in:
$ __python2 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./beta/api/korbit/vnkorbit.py:76:13: F821 undefined name 'logging'
logging.error("exception: {}, response_text: {}".format(e, response.text))
^
./examples/VnTrader/run.py:54:23: F821 undefined name 'xtpGateway'
me.addGateway(xtpGateway)
^
./vnpy/trader/gateway/lbankGateway/__init__.py:6:16: F821 undefined name 'lbankGateway'
gatewayClass = lbankGateway
^
3     F821 undefined name 'logging'
3
```
=> Fix undefined name xtpGateway (to dev this time)

.travis.yml
Step 1 of #818
There are tons of tools in the [GitHub Marketplace](https://github.com/marketplace) but the one that I use the most is [Travis CI](https://travis-ci.org) because it is free for Open Source projects like this one and it is quite flexible at running tests.  This config file has Travis run [flake8](http://flake8.pycqa.org) tests on every pull request so that we can quickly see if there are breaking changes.  At https://travis-ci.org/profile you would need to flip the switch on for this repo on and then commit any change to the repo for the testing to begin.
=> Add Travis CI to automatically run flake8 tests

examples/FutuDataService/dataService.py, examples/FutuDataService/runService.py, examples/JaqsService/run.py, examples/JaqsService/runUI.py, examples/ServerClient/client.py, examples/ServerClient/server.py, examples/ShcifcoDataService/dataService.py, examples/ShcifcoDataService/runService.py, examples/TqDataService/dataService.py, examples/TqDataService/runService.py, examples/TushareDataService/dataService.py, examples/TushareDataService/runService.py
Run [__futurize --stage1 -w__](http://python-future.org/futurize_cheatsheet.html) on the older examples:
* examples/F*: FutuDataService
* examples/J*: JaqsService
* examples/S*: ServerClient, ShcifcoDataService
* examples/T*: TqDataService, TushareDataService
---
* [__reload()__ was moved to importlib](https://docs.python.org/3/library/importlib.html#importlib.reload) in Python 3 because it was overused and led to difficult to solve bugs.  __reload()__ is being used here to reset the default encoding to utf-8 but this is not needed in Python 3 because utf-8 is already the default.
=> Futurize older examples/F*,J*,S*,T*

examples/CtaBacktesting/runOptimization.py, examples/CtaTrading/runCtaTrading.py, examples/DataRecording/runDataCleaning.py, examples/DataRecording/runDataRecording.py, examples/OptionMaster/run.py, examples/QuantosDataService/dataService.py, examples/QuantosDataService/downloadData.py, examples/QuantosDataService/runService.py, examples/VnTrader/run_simple.py, examples/WebTrader/run.py, examples/WebTrader/server.py
Continue the porting process described in #825
Run [__futurize --stage1 -w__](http://python-future.org/futurize_cheatsheet.html) on the older examples:
* [__reload()__ was moved to importlib](https://docs.python.org/3/library/importlib.html#importlib.reload) in Python 3 because it was overused and led to difficult to solve bugs.  __reload()__ is being used here to reset the default encoding to utf-8 but this is not needed in Python 3 because utf-8 is already the default.
=> Futurize older examples

setup.py
We will require the popular [__six__](https://pypi.org/project/six) module to simplify our support of both Python 2 and Python 3.
=> setup.py: install_requires=['six>=1.11.0']

examples/QuantosDataService/dataService.py
0：00时，人家日期时新的一天，而回退到23：59没有回退日期
1. 
2. 
3.
Close #966
=> 时间回退1分钟，0：00时跨日回退错误

.gitignore
1. 忽略pyenv自动创建的.python-version文件
=> 忽略pyenv自动创建的.python-version文件

.gitignore
1. 增加了一些gitignore
我在清理文件的时候发现了一些build/下的文件，所以就想着要不要把这些文件加进gitignore里面来了。
=> [Fix] 添加gitignore，忽略掉CMake的临时文件，还有build/文件夹

vnpy/trader/gateway/ctpGateway/ctpGateway.py
有时候defineDict['THOST_FTDC_VC_CV']和orderReq.volume的类型为str，最终会导致报单字段有误。
=> [Fix] 某些时候往CTP接口下单，会产生报单字段有误的错误。

vnpy/trader/gateway/huobiGateway/huobiGateway.py
1. 修复火币中tick和newtick混用错误，应该用newtick，此处用的是tick
2. 
3.
Close #
=> [mod] 修复火币中tick和newtick混用错误

vnpy/trader/gateway/bitmexGateway/bitmexGateway.py
[Fix] 修复了当bitmexgateway.socketapi响应onTrade时，遇到side字段为''导致异常的情况。
下面是一个side字段为空的例子：
{
'execID': '***', 'execType': 'Funding',
'ordStatus': 'Filled', 'lastLiquidityInd': '', 'exDestination': 'XBME',
'text': 'Funding',
'lastQty': 508, 'timeInForce': 'AtTheClose', 'currency': 'USD', 'pegPriceType': '',
'simpleLeavesQty': None, 'transactTime': '***', 'ordRejReason': '',
'underlyingLastPx': None, 'execCost': 8051292, 'clOrdID': '', 'settlCurrency': 'XBt',
'cumQty': 508, 'displayQty': None, 'lastPx': 6309.35, 'homeNotional': -0.08051292,
'commission': -0.0001, 'avgPx': 6309.35, 'lastMkt': 'XBME', 'price': 6309.35,
'trdMatchID': '***', 'simpleOrderQty': None,
'contingencyType': '', 'triggered': '', 'timestamp': '***',
'symbol': 'XBTUSD', 'foreignNotional': 508, 'pegOffsetValue': None, 'execInst': …
=> [Fix] 修复了当bitmexgateway.socketapi响应onTrade时，遇到side字段为''导致异常的情况。

vnpy/trader/uiMainWindow.py
[Fix] 修正一个UI错误：修复了最大化app之后关闭再打开会显示一大片空白的问题
[Add] UI功能性增强：点击某个app之后，该app一定会被移到前台。
[Mod] 判断一个app是否打开：去掉了try_catch，改用if
显示一大片空白的根本原因还不知道，但是使用resize(size)能保证解决这个问题。
移动到前台时同时调用了QWidget.raise()和QWidget.activateWindow()。从文档说明上看，activeWindow应该包含了raise()。为了防止activeWindow仅仅是获取焦点，所以一起调用了。即便重复，多调用一次问题也不大。
=> [Fix] 修正一个UI错误：修复了最大化app之后关闭再打开会显示一大片空白的问题

examples/TurtleStrategy/turtleEngine.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
=> Use print() function in both Python 2 and Python 3

.pylintrc
[Mod] constant can be both UPPER_CASE or CamelCase
UPPER_CASE for normal constant, CamelCase for Type aliases.
=> [Mod] constant can be both UPPER_CASE or CamelCase

vnpy/trader/app/ctaStrategy/ctaBacktesting.py
两个修改：
若无成交，calculateBacktestingResult返回的是0，而不是空的字典
calculateBacktestingResult直接获取maxDrawdown的值
=> 修改策略回测引擎calculateBacktestingResult，无交易返回空字典的bug

vnpy/api/ctp/generator/generate_api_functions.py, vnpy/api/ctp/vnctp/vnctp.h, vnpy/api/ctp/vnctp/vnctpmd/vnctpmd.cpp, vnpy/api/ctp/vnctp/vnctpmd/vnctpmd.h, vnpy/api/ctp/vnctp/vnctptd/vnctptd.cpp, vnpy/api/ctp/vnctp/vnctptd/vnctptd.h
关于传参：
可以改为引用的地方全部改为引用，减少一次参数的复制。
关于getString:
strcpy的template特化版本可以在VisualStudio中使用。
关于getXXX中的异常：
异常会被上层捕获。getXXX的调用者全为reqXXXX，其上层为pybind11.
pybind11会将异常转化为python异常然后回传到python之中。所以在C++中不需要特地捕获异常。
=> [Fix] 稍稍改一下ctp到python的转换

vnpy/trader/app/ctaStrategy/ctaBacktesting.py
1. tradeTimeIndex小于10时，将导致ZeroDivisionError。增加一个判断。
2. 在“到最后交易日尚未平仓的交易，则以最后价格平仓”的操作中，以最后价格平仓并把结果加入resultList中，posList和tradeTimeList中也应添加相应数据
3.
Close #
=> [Fix] 修复一处ZeroDivisionError和补充回测结果数据

vnpy/trader/app/algoTrading/algo/stopAlgo.py
stopAlgo 缺少short控制，导致一启动算法就立即发出卖出委托，增加short控制，已修复。
1. 
2. 
3.
Close #
=> stopAlgo 缺少short控制，导致一启动算法就立即发出卖出委托

vnpy/gateway/ctp/ctp_gateway.py
1. CTP无法登陆需要“产品名称、授权编码”验证的期货公司账号，原因是函数authenticate() 和 login() 的"UserProductInfo"参数配置有bug
Close #1554
=> fix a bug in CTP login using UserProductInfo and AuthCode

vnpy/trader/database/database_mongo.py, vnpy/trader/database/database_sql.py
1. 修复多列索引建立顺序错误问题
2. 提高在大数据量情况下的搜索速度
3. 实测，从五千万条数据中，读取某一品种三年的数据，从没修改前的 2分30秒，减少到 12 秒
```shell
(vnpy) ➜  vnpy git:(master) ✗ python backtest.py
2019-05-08 11:22:57.871550      开始加载历史数据
2019-05-08 11:23:09.539976      历史数据加载完成，数据量：175200
```
Close #1662
=> 修复错误多列索引顺序导致大数据查询效率低下问题

.travis.yml, appveyor.yml, install.bat, install.sh, install_osx.sh, setup.py
主要修改：
[Add] install.sh增加升级pip的脚本，以确保能正确安装各个pip包（可能会导致Ubuntu下/usr/bin/pip3失效）
[Mod] 使用python -m pip 来运行pip，以确保在/usr/bin/pip3失效时脚本仍然正常运行
[Mod] 在setup.py中使用psycopg2-binary替代psycopg2，并且只有在psycopg2包不不存在时安装。
=> [Mod] 改进Linux的构建脚本

vnpy/event/eventEngine.py
客户端不使用定时器
初始化, MainEngineProxy(EventEngine2()) -> EventEngine2.start(timer=False).
退出时, MainEngineProxy.stop() -> EventEngine2.stop(), 此时Timer线程并没有启动, 就报错了.
所以需要加判断条件: 在Timer启用的情况下, 再停止Timer线程
=> fix bug: RPC客户端不使用定时器, 造成调用EventEngine2.stop()报错

vnpy/gateway/tiger/tiger_gateway.py
1. 行情推送的时间撮，由last_time 变成 timestamp
=> [Fix] 修复老虎接口行情推送的bug

vnpy/app/cta_strategy/converter.py
1. 上期所模式中，平仓量超过总可用，拒绝，返回空列表，而不是【Req】
2. 锁仓模式，若无今仓，先平昨仓再开仓。该开仓量大小应为max(0, req.volume - yd_available)，而不是max(0, yd_available - req.volume)
=> [Mod] 修复converter的bug

vnpy/app/cta_strategy/template.py
1. 通过策略类多次构建实例，因variables是类变量，在CtaTemplate的__init__中会对variables重复赋值。
=> 解决类变量重复赋值的Bug

vnpy/app/script_trader/cli.py
`init_cli_trading` 中，参数 `gateways` 的类型应该是 `BaseGateway` 类
`Sequence[BaseGateway]` 表示一个列表的 `BaseGateway` 对象，在 pycharm 中会报 warning
`Sequence[Type[BaseGateway]]` 则表示一个列表的 `BaseGateway` 类，与真实语义相符
=> [Fix] 修复 init_cli_trading 的 type hint

vnpy/gateway/bybit/bybit_gateway.py
1. query_history 函数有时返回空列表，导致策略初始化失败
=> [Fix] query_history

vnpy/app/cta_strategy/backtesting.py
修复优化时max_drawdown_end可能为nan导致程序出错,顺便转化statistics可能出现的nan,inf值
=> 修复优化时max_drawdown_end可能为nan导致程序出错,顺便转化statistics可能出现的nan,inf值

vnpy/gateway/ctptest/ctptest_gateway.py
修正CTP Test撤单时报的类型转换异常: RuntimeError: Unable to cast Python instance to C++ type
cancel_order方法中的ExchangeID字段传入req.exchange.value应该就不出错了。
=> 修正CTP Test撤单时报的类型转换异常: RuntimeError: Unable to cast Python instance to C++ type

vnpy/gateway/okex/okex_gateway.py
修复参数拼写错误，该错误会导致OKEX接口下的「行情」中的参数（开盘价、最高价、最低价）缺失。
=> [Fix] typo

vnpy/app/cta_backtester/engine.py, vnpy/app/cta_strategy/__init__.py
cta_strategy 引入了 backtesting，其又 import 了一些较大的包，有些与图形相关，如果只是跑 CTA 策略我们并不需要图形相关的功能。根据最小依赖原则，可以去掉。其他引入 backtesting 的地方只有 cta_backtester，不影响已有功能。
因为 backtesting 是在 cta_strategy 的 `__init__.py` 中 import 的，我们如果不改源码无法绕过这个问题，修改之后对定制化开发者比较友好。
=> do not import backtesting

vnpy/trader/utility.py
1. 对于商品期货 11:30午间休市，13:30下午开盘，只判断minute会导致11:30的tick被吸收到下午的分钟bar里去。修改后的分钟数据，与wind的数据一致。
=> fix(BarGenerator): new minute bug

vnpy/gateway/ib/ib_gateway.py
1. 过滤order返回为Nonetype时ib_gateway挂掉的情况.
2. 
3.
Close #
=> Update ib_gateway.py: 过滤order返回为Nonetype时ib_gateway挂掉的情况.

vnpy/chart/widget.py
1. `vnpy.chart.widget.ChartWidget`中，若一个plot中添加了多个item，plot的y轴范围会按照最后添加的item的y轴范围来设置。如果最后添加的item的y轴最大、最小值不能包含其它item的y轴范围时，会导致其它item的图像无法完整显示。
此处我通过修改`vnpy.chart.widget.ChartWidget`的`_update_plot_limits()`和`_update_y_range()`方法，在设置plot的item范围时，汇总plot中所有item的y轴最大最小值后再设置，保证所有item的图像都能完整显示。
2. `vnpy.chart.widget.ChartCursor`中，光标所在位置的提示信息框始终显示在plot的左上角，如果在左上角有图形，则左上角的图形会始终被信息提示框遮挡而无法看到。
此处我通过修改`vnpy.chart.widget.ChartCursor`的`update_info()`方法，根据光标所在位置来调整信息提示框的位置。如果光标在绘图控件的右半侧，则信息提示框依然显示在plot的左上角。当光标在绘图控件左半侧，则信息提示框显示在plot的右上角，从而解决左上角图像可能始终被遮挡的问题。
=> Backtester ui

vnpy/chart/widget.py
```python
Traceback (most recent call last):
File "run.py", line 22, in <module>
widget.add_plot("volume", maximum_height=200)
File "/Users/chandler/.pyenv/versions/3.8.1/lib/python3.8/site-packages/vnpy/chart/widget.py", line 72, in add_plot
plot = pg.PlotItem(axisItems={'bottom': self._x_axis})
File "/Users/chandler/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 159, in __init__
self.setAxisItems(axisItems)
File "/Users/chandler/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 329, in setAxisItems
raise RuntimeError(
RuntimeError: Can't add an axis to multiple plots. Shared axes can be achieved with multiple AxisItem instances and set[X/Y]Link.
```
1. …
=> [Fix] Fix Charts to support pyqtgraph==0.11.1

vnpy/gateway/huobis/huobis_gateway.py
修复HuobisGateway的ConnectionResetError问题，通过关闭HTTP连接的keep-alive功能实现
=> 修复HuobisGateway的ConnectionResetError问题

vnpy/app/spread_trading/backtesting.py
1. 由于vnstudio自带pandas版本过旧，使用时出现TypeError: Cannot interpret ‘＜attribute ‘dtype‘ of ‘numpy.generic‘ objects＞‘ as a data type，故手动进行升级，结果发现回测报错，发现升级之后argmax()定义已经出现变化，参考portfolio_strategy那边的回测代码改用idxmax()，代码中除了此处没有其它地方使用argmax()
Close #
=> argmax() to idxmax()

vnpy/api/websocket/websocket_client.py, vnpy/app/spread_trading/engine.py, vnpy/gateway/bitfinex/bitfinex_gateway.py, vnpy/gateway/bitmex/bitmex_gateway.py, vnpy/gateway/coinbase/coinbase_gateway.py, vnpy/gateway/gateios/gateios_gateway.py, vnpy/gateway/hsoption/hsoption_gateway.py, vnpy/gateway/onetoken/onetoken_gateway.py, vnpy/rpc/__init__.py
There are small typos in:
- vnpy/api/websocket/websocket_client.py
- vnpy/app/spread_trading/engine.py
- vnpy/gateway/bitfinex/bitfinex_gateway.py
- vnpy/gateway/bitmex/bitmex_gateway.py
- vnpy/gateway/coinbase/coinbase_gateway.py
- vnpy/gateway/gateios/gateios_gateway.py
- vnpy/gateway/hsoption/hsoption_gateway.py
- vnpy/gateway/onetoken/onetoken_gateway.py
- vnpy/rpc/__init__.py
Fixes:
- Should read `websocket` rather than `websockey`.
- Should read `websocket` rather than `webscoket`.
- Should read `subscribe` rather than `subscrbe`.
- Should read `function` rather than `fuction`.
- Should read `function` rather than `fucntion`.
- Should read `enough` rather than `enougth`.
- Should read `currency` rather than `currenct`.
- Should read `update` rather than `upate`.
- Should read …
=> docs: Fix a few typos

vnpy/gateway/rpc/rpc_gateway.py
1. 策略初始化的时候一般需要通过load_bars载入一部分历史数据，这里修改RpcGateway使得策略可以通过服务端获取历史数据
Close #
=> [Fix] RpcGateway增加从远程服务端获取历史数据功能

README_ENG.md
fix GitHub workflow badge URL.
See https://github.com/badges/shields/issues/8671
> You need to update your badge URL from
> https://img.shields.io/github/workflow/status/<user>/<repo>/Run%20Tests
> to
> https://img.shields.io/github/actions/workflow/status/<user>/<repo>/test.yml?branch=main
=> fix GitHub workflow badge URL.

vnpy/trader/utility.py
fix
```
Traceback (most recent call last):
File "/home/baozhu/storage/MoneyGrove/a_main.py", line 170, in <module>
main()
~~~~^^
File "/home/baozhu/storage/MoneyGrove/a_main.py", line 146, in main
conditions_met, indicators = check_conditions(bars)
~~~~~~~~~~~~~~~~^^^^^^
File "/home/baozhu/storage/MoneyGrove/a_main.py", line 93, in check_conditions
k, d = am.stoch(9, 3, 0, 3, 0, array=True)  # Correct parameters order: fastk_period, slowk_period, slowk_matype, slowd_period, slowd_matype
~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/baozhu/anaconda3/envs/vnpy/lib/python3.13/site-packages/vnpy/trader/utility.py", line 1090, in stoch
talib.MA_Type(slowk_matype),
~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'MA_Type' object is not callable
```
1. 
2. 
3. …
=> [fix] MA_Type object is not callable
