vnpy/vnpy

vn.trader/ibGateway/ibGateway.py
vn.trader/riskManager/rmEngine.py
vn.trader/uiBasicWidget.py

1. Fix mac 运行出错, 只在windows提示声音. 2. IB价格变化的时候更新行情事件 3. UI增加昨天收盘价和外汇

1. Fix mac 运行出错, 只在windows提示声音. 2. IB价格变化的时候更新行情事件 3. UI增加昨天收盘价

---

README.md

添加一个明确的contribute process来规范，鼓励更多的人贡献代码

添加关于如何贡献代码的guideline

---

README.md

这在qq群里基本上每天都会被新人问到 - 放在主页可以节省不少时间

添加关于WIND, IB, OKCOIN三个接口的安装指南

---

vn.okcoin/vnokcoin.py
vn.trader/okcoinGateway/vnokcoin.py

修正futureOrderInfo方法的小Bug

---

vn.trader/ibGateway/ibGateway.py
vn.trader/uiBasicWidget.py
vn.trader/vtConstant.py
vn.trader/vtGateway.py

1.添加了港币币种数据字典HKD，指数品种数据字典IND
2.添加了相关期货交易所数据字典HXFE
3.由于测试了港股的股指期货，IbGateway中的sendorder函数添加了contract.lastTradeDateOrContractMonth、contract.multiplier两个参数的支持

测试了ib接口香港期货交易所期货品种的行情及交易接口，添加对应数据字典、接口参数支持

---

vn.trader/ctaAlgo/ctaHistoryData.py

通达信的历史数据导出功能可免费获取股票、期货的历史分钟数据，这里提供将导出的历史分钟数据插入MongoDB的函数

新增通达信分钟数据载入MongoDB

---

vn.trader/ctaAlgo/ctaHistoryData.py

tushare下载沪深股票日行情

---

vn.trader/vtServer.py

方法名写错了，已改qryAccont->qryAccount

方法名写错了，已改qryAccont->qryAccount

---

vn.trader/ctaStrategy/ctaEngine.py
vn.trader/ctaStrategy/strategy/strategyKingKeltner.py

ctaEngine中的typo修改，以及KK策略中平空函数修正

typo & error in kk strategy

---

vnpy/data/shcifco/vnshcifco.py

bugfix：
1. getlasttick 空数据判断失误导致后续分析异常 
2. gethisbar 日期关键字更改为tradingday
上述修复全部测试通过

bugfix:  函数 getlasttick  gethisbar 

---

vnpy/trader/uiQt.py

1、修改QtUi的BUG，其他模块引用不到BASIC_FONT

修改QtUi的BUG，其他模块找不到BASIC_FONT，把BASIC_FONT的初始化从函数内移到函数外

---

vnpy/api/ib/vnib/vnib/vnib.cpp
vnpy/trader/app/ctaStrategy/tools/ctaLineBar.py

class_<std::vector<ibapi::shared_ptr<OrderCondition>>>("OrderConditionList")
-		.def(vector_indexing_suite<std::vector<ibapi::shared_ptr<OrderCondition>>, true>());
- 重复定义了。 删除一行。

class_<std::vector<ibapi::shared_ptr<OrderCondition>>> 定义重复，删除一行

---

.gitignore

忽略vscode项目配置目录

---

vnpy/trader/vtEngine.py

主数据引擎订单完成状态包含拒单

---

vnpy/trader/app/ctaStrategy/ctaHistoryData.py

增加将OKEX下载的数据导入到数据库

---

vnpy/data/tq/test.py
vnpy/data/tq/vntq.py

1. 针对天勤接口协议中合约代码规则变更, 相应调整demo及文档说明
Close #793

针对天勤接口协议中合约代码规则变更, 相应调整demo及文档说明

---

examples/TqDataService/config.json
examples/TqDataService/dataService.py
examples/TqDataService/downloadData.py
examples/TqDataService/runService.py
vnpy/data/tq/vntq.py

天勤0.8版修改了合约代码规则后, vnpy接口中的示例未相应修改, 导致不能正常获取数据

修正天勤数据接口不能正常获取数据的bug

---

vnpy/data/datayes/__init__.py
vnpy/data/datayes/vndatayes.py
vnpy/data/shcifco/test.py
vnpy/data/shcifco/vnshcifco.py
vnpy/data/tq/test.py
vnpy/data/tq/vntq.py

Run [__futurize --stage1 -w__](http://python-future.org/futurize_cheatsheet.html) on the __vnpy/data__ directory:
* from six import input instead of __raw_input()__

Modernize vnpy/data

---

beta/api/coincheck/__init__.py
beta/api/coincheck/test.py
beta/api/coincheck/test2.py
beta/api/coincheck/test3.py
beta/api/coincheck/test4.py
beta/api/coincheck/vncoincheck.py
beta/api/korbit/__init__.py
beta/api/korbit/korbit-python-master/korbit/private_api.py
beta/api/korbit/korbit-python-master/korbit/public_api.py
beta/api/korbit/korbit-python-master/korbit/test.py
beta/api/korbit/test.py
beta/api/korbit/vnkorbit.py
beta/api/okex/__init__.py
beta/api/okex/test.py
beta/api/okex/vnokex.py
beta/api/zaif/__init__.py
beta/api/zaif/test.py
beta/api/zaif/vnzaif.py
beta/api/zb/__init__.py
beta/api/zb/test.py
beta/api/zb/vnzb.py
beta/gateway/coincheckGateway/__init__.py
beta/gateway/coincheckGateway/coincheckGateway.py
beta/gateway/korbitGateway/__init__.py
beta/gateway/korbitGateway/korbitGateway.py
beta/gateway/okexGateway/__init__.py
beta/gateway/okexGateway/okexGateway.py
beta/gateway/zbGateway/__init__.py
beta/gateway/zbGateway/zbGateway.py
beta/spreadtrading/stBase.py

Run [__futurize --stage1 -w__](http://python-future.org/futurize_cheatsheet.html) on the __beta__ directory:
* Old style exceptions to new style
* from six import xrange

Modernize beta

---

vnpy/api/cshshlp/__init__.py
vnpy/api/cshshlp/test/cstest.py
vnpy/api/ctp/__init__.py
vnpy/api/ctp/py3/pyscript/generate_data_type.py
vnpy/api/ctp/py3/pyscript/generate_td_functions.py
vnpy/api/ctp/pyscript/generate_data_type.py
vnpy/api/ctp/pyscript/generate_td_functions.py
vnpy/api/ctp/vnctpmd/test/mdtest.py
vnpy/api/ctp/vnctptd/test/tdtest.py
vnpy/api/femas/__init__.py
vnpy/api/femas/pyscript/generate_data_type.py
vnpy/api/femas/vnfemasmd/test/mdtest.py
vnpy/api/femas/vnfemastd/test/tdtest.py
vnpy/api/fxcm/__init__.py
vnpy/api/fxcm/test.py
vnpy/api/fxcm/vnfxcm.py

Modernize vnpy/api/c* and vnpy/api/f*

---

vnpy/api/lbank/__init__.py
vnpy/api/lbank/test.py
vnpy/api/lbank/vnlbank.py
vnpy/api/lts/__init__.py
vnpy/api/lts/pyscript/generate_data_type.py
vnpy/api/lts/pyscript/l2/generate_data_type.py
vnpy/api/lts/vnltsmd/test/mdtest.py
vnpy/api/lts/vnltsqry/test/qrytest.py
vnpy/api/lts/vnltstd/test/tdtest.py

Modernize vnpy/api/l*

---

vnpy/api/ksgold/__init__.py
vnpy/api/ksgold/pyscript/generate_data_type.py
vnpy/api/ksgold/pyscript/generate_struct.py
vnpy/api/ksotp/__init__.py
vnpy/api/ksotp/pyscript/generate_data_type.py
vnpy/api/ksotp/pyscript/generate_struct.py
vnpy/api/ksotp/vnksotpmd/test/mdtest.py
vnpy/api/ksotp/vnksotptd/test/tdtest.py

Modernize vnpy/api/k*

---

vnpy/api/oanda/__init__.py
vnpy/api/oanda/test.py
vnpy/api/oanda/vnoanda.py
vnpy/api/qdp/__init__.py
vnpy/api/qdp/pyscript/generate_data_type.py
vnpy/api/qdp/pyscript/generate_td_functions.py

Modernize vnpy/api/o* and q*

---

vnpy/api/shzd/__init__.py
vnpy/api/shzd/test/test.py

Modernize vnpy/api/shzd

---

vnpy/api/xtp/__init__.py
vnpy/api/xtp/pyscript/generate_data_type.py
vnpy/api/xtp/pyscript/generate_md_functions.py
vnpy/api/xtp/pyscript/generate_struct_oms.py
vnpy/api/xtp/pyscript/generate_struct_quote.py
vnpy/api/xtp/pyscript/generate_td_functions.py
vnpy/api/xtp/test/quotetest.py
vnpy/api/xtp/test/tradertest.py

Modernize vnpy/api/xtp

---

vnpy/api/xspeed/__init__.py
vnpy/api/xspeed/pyscript/generate_data_type.py
vnpy/api/xspeed/pyscript/generate_md_functions.py
vnpy/api/xspeed/pyscript/generate_struct.py
vnpy/api/xspeed/pyscript/generate_td_functions.py
vnpy/api/xspeed/pyscript/old/generate_data_type.py
vnpy/api/xspeed/pyscript/old/generate_struct.py
vnpy/api/xspeed/test/xspeedmdtest.py
vnpy/api/xspeed/test/xspeedtdtest.py

Modernize vnpy/api/xspeed

---

vnpy/api/sec/__init__.py
vnpy/api/sec/pyscript/generate_data_type.py
vnpy/api/sec/pyscript/generate_md_functions.py
vnpy/api/sec/pyscript/generate_struct.py
vnpy/api/sec/pyscript/generate_td_functions.py
vnpy/api/sec/test/md_test.py
vnpy/api/sec/test/td_test.py

Modernize vnpy/api/sec

---

vnpy/trader/app/ctaStrategy/ctaBacktesting.py
vnpy/trader/app/ctaStrategy/ctaHistoryData.py
vnpy/trader/app/ctaStrategy/language/__init__.py
vnpy/trader/app/ctaStrategy/strategy/__init__.py
vnpy/trader/app/dataRecorder/__init__.py
vnpy/trader/app/dataRecorder/language/__init__.py
vnpy/trader/app/jaqsService/__init__.py
vnpy/trader/app/jaqsService/jrpc_server.py
vnpy/trader/app/jaqsService/jsEngine.py
vnpy/trader/app/jaqsService/service.py
vnpy/trader/app/optionMaster/omDate.py
vnpy/trader/app/optionMaster/strategy/__init__.py
vnpy/trader/app/optionMaster/uiOmManualTrader.py
vnpy/trader/app/optionMaster/uiOmWidget.py
vnpy/trader/app/riskManager/__init__.py
vnpy/trader/app/riskManager/language/__init__.py
vnpy/trader/app/spreadTrading/uiStWidget.py

Run [__futurize --stage1 -w__](http://python-future.org/futurize_cheatsheet.html) on the __vnpy/trader/app__ directory:
* new style exceptions
* __from six import text_type__ instead of __unicode()__
* bypass __reload()__ on Python 3

Modernize vnpy/trader/app

---

examples/WebTrader/README.md

[Mod]更新WebTrader使用说明

---

.travis.yml
vnpy/api/binance/test.py
vnpy/api/binance/vnbinance.py
vnpy/api/bitfinex/vnbitfinex.py
vnpy/api/huobi/vnhuobi.py
vnpy/api/sgit/__init__.py
vnpy/event/eventEngine.py
vnpy/event/eventType.py
vnpy/rpc/testClient.py
vnpy/rpc/testServer.py
vnpy/trader/app/algoTrading/twapAlgo.py
vnpy/trader/app/algoTrading/uiAlgoManager.py
vnpy/trader/app/algoTrading/uiAlgoWidget.py
vnpy/trader/gateway/binanceGateway/binanceGateway.py
vnpy/trader/vtFunction.py

Run __futurize --stage1 -w__ on the entire repo.

Modernize Python 2 code to get ready for Python 3

---

vnpy/api/bitmex/vnbitmex.py
vnpy/trader/app/algoTrading/dmaAlgo.py
vnpy/trader/app/algoTrading/stopAlgo.py
vnpy/trader/gateway/bitmexGateway/bitmexGateway.py

Run __futurize --stage1 -w .__ on the entire repo yet again.

Modernize recent changes

---

vnpy/api/bithumb/__init__.py
vnpy/api/bithumb/vnbithumb.py

[Add]新增Bithumb API

---

vnpy/api/ctp/vnctpmd/vnctpmd/vnctpmd.cpp

[Fix] 优化了ctp接口py转换层的性能
1.使用特化版的strcpy_s，提升拷贝性能
2.使用引用，避免重复的string拷贝

[Fix] 优化了ctp接口py转换层的性能

---

vnpy/trader/gateway/ctpGateway/ctpGateway.py

1. [Mod]ctpGateway的Python3兼容性修改
2. 
3.
Close #

[Mod]ctpGateway的Python3兼容性修改

---

beta/api/coincheck/vncoincheck.py
beta/api/korbit/vnkorbit.py
beta/api/zaif/vnzaif.py
beta/gateway/coincheckGateway/coincheckGateway.py
beta/gateway/korbitGateway/korbitGateway.py
beta/gateway/zbGateway/zbGateway.py
beta/quantos/app/jaqsService/jrpc_server.py
beta/quantos/tkproGateway/DataApi/jrpc_py.py
beta/quantos/tkproGateway/TradeApi/jrpc_py.py
vnpy/api/lbank/vnlbank.py
vnpy/trader/app/dataRecorder/drEngine.py

[Mod]统一使用queue

---

beta/gateway/coincheckGateway/coincheckGateway.py
beta/gateway/korbitGateway/korbitGateway.py
beta/gateway/zbGateway/zbGateway.py
beta/quantos/tkproGateway/tkproGateway.py
vnpy/trader/gateway/bigoneGateway/bigoneGateway.py
vnpy/trader/gateway/binanceGateway/binanceGateway.py
vnpy/trader/gateway/bitfinexGateway/bitfinexGateway.py
vnpy/trader/gateway/bithumb/bithumbGateway.py
vnpy/trader/gateway/bitmexGateway/bitmexGateway.py
vnpy/trader/gateway/ccxtGateway/ccxtGateway.py
vnpy/trader/gateway/coinbaseGateway/coinbaseGateway.py
vnpy/trader/gateway/cshshlpGateway/cshshlpGateway.py
vnpy/trader/gateway/fcoinGateway/fcoinGateway.py
vnpy/trader/gateway/femasGateway/femasGateway.py
vnpy/trader/gateway/fxcmGateway/fxcmGateway.py
vnpy/trader/gateway/ibGateway/ibGateway.py
vnpy/trader/gateway/ksgoldGateway/ksgoldGateway.py
vnpy/trader/gateway/ksotpGateway/ksotpGateway.py
vnpy/trader/gateway/lbankGateway/lbankGateway.py
vnpy/trader/gateway/ltsGateway/ltsGateway.py
vnpy/trader/gateway/okexGateway/okexGateway.py
vnpy/trader/gateway/qdpGateway/qdpGateway.py
vnpy/trader/gateway/secGateway/secGateway.py
vnpy/trader/gateway/sgitGateway/sgitGateway.py
vnpy/trader/gateway/shzdGateway/shzdGateway.py
vnpy/trader/gateway/xspeedGateway/xspeedGateway.py
vnpy/trader/gateway/xtpGateway/xtpGateway.py

1. [Mod]gateway相关的python3兼容性修改
2. 
3.
Close #1064

[Mod]gateway相关的python3兼容性修改

---

vnpy/trader/app/spreadTrading/uiStWidget.py

[Fix] 改回丢失的状态按钮

---

vnpy/trader/gateway/ctpGateway/ctpGateway.py

[Fix] ctpGateway: 修正一个在查询持仓时，若未查询过该合约大小则出错的BUG

[Fix] ctpGateway: 修正一个在查询持仓时，若未查询过该合约大小则出错的BUG

---

vnpy/trader/app/algoTrading/AlgoUiHelper.py

[Add] 为AlgoTrading增加能够自动生成UI的辅助代码

[Add] 为AlgoTrading增加能够自动生成UI的辅助代码

---

vnpy/trader/uiMainWindow.py

[Add] 新增openApp系列函数

---

vnpy/trader/gateway/bitmexGateway/bitmexGateway.py

[Fix] 修正市价单无法下单的问题

---

vnpy/trader/app/algoTrading/algo/arbitrageAlgo.py

1. 此处应该为passiveVtSymbol，这样符合套利的整体逻辑。
Close #

套利交易逻辑对冲函数逻辑被动腿错误

---

tests/api/base/RestClientTest.py
tests/api/base/WebSocketClientTest.py
vnpy/api/okexfuture/OkexFutureApi.py
vnpy/api/okexfuture/__init__.py
vnpy/api/okexfuture/vnokexFuture.py
vnpy/api/rest/RestClient.py
vnpy/api/websocket/WebSocketClient.py
vnpy/api/websocket/__init__.py
vnpy/trader/gateway/okexFutureGateway/okexFutureGateway.py
vnpy/trader/vtObject.py

上周五和今天的工作。
主要有这些修改：
1、okexfuturegateway增加了一些功能
2、okexfutureapi的一些改进
3、底层的restclient命名修改
4、底层websocketclient的修改
5、VtObject增加了一些staticmethod

Okex.websocketclient.devel

---

docker/gui/Dockerfile
docker/gui/README.md
docker/gui/build.sh
docker/gui/run.sh
requirements.txt

1. 可在 Docker 里面直接运行 vnpy 程序，支持 qt 渲染
2. 
3.
Close #

增加 Docker GUI 支持

---

vnpy/api/rest/RestClient.py
vnpy/api/websocket/WebsocketClient.py

[Mod] 将websocket._connect移动到工作线程中
[Mod] 修改错误处理方式：onError将会捕捉更多异常
onError目前比以前能够多捕获两种异常：
* websocket首次连接时的异常
* RestClient._createSession中产生的异常

[Mod] 将websocket._connect移动到工作线程中

---

.travis.yml
vnpy/trader/gateway/ctpGateway/ctpGateway.py

1. 改进通过 CTP 获取股票期权 tick 数据，包括五档报价
2. 改进通过 CTP 获取股票期权 tick 数据，获得当日日期逻辑

优化 ctp 股票期权 tick 数据获取

---

tests/api/base/RestClientTest.py
tests/api/base/WebSocketClientTest.py
vnpy/api/rest/RestClient.py
vnpy/api/websocket/WebsocketClient.py
vnpy/trader/app/ctaStrategy/strategy/__init__.py
vnpy/trader/gateway/bitmexGateway/bitmexGateway.py

[Add] 在RestClient.addRequest中增加onError参数，可以重定向onError回调。
[Add] 在WebSocketClient, RestClient的错误处理函数中打印更多的详细信息
[Add] 增加RestClient.printExceptionDetail和WebSocketClient.printExceptionDetail，用于打印详细的错误信息
[Mod] 修改了对应的测试样例

[Add] 在RestClient.addRequest中增加onError参数，可以重定向onError回调。

---

vnpy/api/websocket/WebsocketClient.py
vnpy/trader/gateway/okexFuturesGateway/OkexFuturesBase.py
vnpy/trader/gateway/okexFuturesGateway/okexFuturesGateway.py

[Fix] 修复对OkexWebSocket的支持：OkexWebSocket强制启用了zlib压缩
[Add] 增加了WebSocketClient.unpackData，用于自定义解包方法。默认解包方式为json.loads

[Fix] Okex compressed websocket

---

vnpy/trader/gateway/bitmexGateway/bitmexGateway.py

[Mod] 修改：BitmexGateway出错时将会在stderr里面打印更详细的错误信息

[Mod] 修改：BitmexGateway出错时将会在stderr里面打印更详细的错误信息

---

vnpy/api/websocket/WebsocketClient.py

[Fix] 修复一个BUG：websocket在发送ping包时出错将不会重连，导致后续每ping一次报一次错。

[Fix] 修复一个BUG：websocket在发送ping包时出错将不会重连，导致后续每ping一次报一次错。

---

vnpy/trader/app/ctaStrategy/ctaEngine.py

1. 修复初始化策略后界面不更新inited值
2. 
3.
Close #

* 修复初始化策略后界面不更新inited值

---

beta/gateway/huobiGateway/huobiGateway.py

基于新的RestClient和WebSocketClient重写了huobiGateway的底层

[Add] 基于新的RestClient和WebSocketClient重写了huobiGateway的底层

---

.pylintrc
.style.yapf

[Add] .pylintrc
[Add] .style.yapf

[Add] .pylintrc

---

binding/build.bat
binding/doc/build.windows.md
binding/generator/adaptor/ctpadaptor.py
binding/generator/autocxxpy/cxxparser.py

[Add] CXXParser: 增加include路径的设置
[Mod] CXXParser与CXXFileParser互换名字

generator.binding:CXXParser:增加include路径的设置

---

vnpy/app/cta_strategy/strategies/boll_channel_strategy.py

1. [Add] boll_channel_strategy

[Add] boll_channel_strategy

---

vnpy/app/cta_strategy/strategies/atr_rsi_strategy.py

[Add] atr_rsi_strategy.py

---

vnpy/app/cta_strategy/template.py

1. [Add] class CtaSignal
2. [Add] class TargetPosTemplate

[Mod] template.py

---

vnpy/app/cta_strategy/strategies/double_ma_strategy.py

1. Mod double_ma_strategy.py
Close #

[Mod] double_ma_strategy

---

vnpy/app/cta_strategy/strategies/multi_signal_strategy.py

1. [Add] multi_signal_strategy

[Add] multi_signal_strategy

---

setup.py

[Mod] setup.py: should not build under windows

[Mod] setup.py: should not build under windows

---

docs/conf.py

* [Mod] change docs style
* [Del] Removed extra blank lines

[Mod] change docs style

---

tests/trader/run.py
vnpy/gateway/tiger/__init__.py
vnpy/gateway/tiger/tiger_gateway.py

[Add] Tiger gateway

---

vnpy/gateway/tiger/tiger_gateway.py

1. 用信息推送代替主动轮寻，速度大幅提高
2. 仍未解决的bug，一个发单成功，委托界面和成交界面收到2条信息，主要原因的委托号不同
3. 修复若干bug

[Mod] tiger_gateway.py

---

vnpy/trader/gateway/ctpGateway/ctpGateway.py

1. 语法错误，删除多余符号":"
2. 
3.
Close #

[Fix] 语法错误，删除多余符号":"

---

vnpy/api/rest/rest_client.py
vnpy/api/websocket/websocket_client.py
vnpy/trader/gateway.py

[Add] some comments and type hint for RestClient, WebSocketClient and BaseGateway
[Del] remove useless lock in websocket. BTW, Increased stablity of websocket.

Type hint and docs for RestClient, WebSocketClient and BaseGateway.

---

vnpy/gateway/bitmex/bitmex_gateway.py

[Mod] BitmexGateway: send_order added a lock to order_count to make this function thread-safe.
[Add] Added some comments.
[Mod] rename session into session_number.

Bitmex optimize

---

vnpy/api/rest/rest_client.py

[Mod] 修复rest_client.py里错误字段

---

vnpy/app/csv_loader/__init__.py
vnpy/app/csv_loader/ui/csv_loader.ui
vnpy/app/csv_loader/ui/csv_loader_widget.py
vnpy/app/csv_loader/ui/uic/uic_csv_loader.py

[Add] Disable maximun button
[Add] Added an icon
[Add] Popup an message if market data is fully loaded
[Mod] combobox: remove Prefix
[Mod] rename: CSV行情载入器

Optimize CSV loader

---

.travis.yml

[Mod] prevent travis vm from terminating: change -qq into -y

[Mod] prevent travis vm from terminating: change -qq into -y

---

vnpy/gateway/oes/oes_gateway.py
vnpy/gateway/oes/oes_md.py
vnpy/gateway/oes/oes_td.py

[Mod] OesGateway: 使用推送的初始化信息，而不是主动查询
[Mod] OesGateway: 改变部分函数名，跟vnpynic
[Fix] 修正已撤单状态订单的数量不正确的问题
[Fix] 修正初始化订单中状态为撤单的订单时间表示不一致的问题

[Mod] OesGateway: 使用推送的初始化信息，而不是主动查询

---

requirements.txt

[Mod] requirements.txt: use cdn for wheels

[Mod] requirements.txt: use cdn for wheels

---

vnpy/app/cta_strategy/strategies/multi_signal_strategy.py
vnpy/app/cta_strategy/strategies/multi_timeframe_strategy.py
vnpy/app/cta_strategy/strategies/test_strategy.py

[FIX] 修改multi_signal, multi_timeframe 和test Strategy的代码风格

---

vnpy/gateway/okex/__init__.py
vnpy/gateway/okex/okex_gateway.py
vnpy/trader/constant.py

[Add]okex gateway

---

vnpy/rpc/__init__.py
vnpy/rpc/test_client.py
vnpy/rpc/test_server.py
vnpy/rpc/vnrpc.py

1. 驼峰式命名改成下划线命名
2. 修改英文注释
3.修复代码风格符合flake8

[Add] RPC 模块

---

.travis.yml
install.bat
requirements.txt

[Fix] fix travis-ci on master branch

---

vnpy/api/websocket/websocket_client.py

1. websocket默认ping间隔为60秒，无法满足某些交易所需求。（如OKEX 的ping间隔需要在30秒以内）
2. 因此增加了一个变量，用来控制ping的时间间隔，默认为60秒。

[Add] ping_interval

---

vnpy/gateway/huobi/__init__.py
vnpy/gateway/huobi/huobi_gateway.py
vnpy/trader/constant.py

[Add]Huobi gateway

---

tests/backtesting/genetic_algorithm.ipynb
vnpy/app/cta_strategy/backtesting.py
vnpy/gateway/tiger/tiger_gateway.py

1. 增加基于单进程的遗传算法模块
2. 修复backtesting文件用于兼容遗传算法

[Add]遗传算法模块

---

docs/install.md

[Mod] install.md

---

docs/quickstart.md

[Mod] quickstart.md

---

vnpy/trader/engine.py
vnpy/trader/ui/mainwindow.py
vnpy/trader/utility.py

[Mod] 改变Singleton的使用说明
[Mod] 改变路径相关函数的命名

[Mod] 改变utility里的一些细节

---

docs/csv_loader.md

[Add] csv_loader.md

---

docs/cta_strategy.md

[Add] cta策略说明文档

---

vnpy/app/csv_loader/engine.py

CSV_load.py里面engine文件，字符串有单引号 该成 双引号

---

docs/install.md

[Fix] install.md

---

vnpy/gateway/bitfinex/__init__.py
vnpy/gateway/bitfinex/bitfinex_gateway.py
vnpy/trader/constant.py

[Add] Bitfinex_gateway

---

vnpy/gateway/onetoken/onetoken_gateway.py

1. add Onetoken gateway
2. 请注意连接1token时添加了‘账户’和‘交易所’参数，必填 举例：账户: mock-example 交易所：okex
3.下单代码举例: btc.usdt, btc.usd.t等
Close #

Onetoken gateway

---

.travis.yml
appveyor.yml
install.bat
install.sh
requirements.txt
setup.py
tests/trader/test_database.py
vnpy/trader/database/database.py
vnpy/trader/database/database_mongo.py
vnpy/trader/database/database_sql.py
vnpy/trader/utility.py

[Add] DatabaseManager.get_newest_bar_data
[Add] DatabaseManager.get_newest_tick_data
[Add] 依赖项中增加rqdatac

[Add] DatabaseManager.get_newest_xxx_data

---

vnpy/gateway/bitfinex/bitfinex_gateway.py
vnpy/gateway/huobi/huobi_gateway.py
vnpy/gateway/okex/okex_gateway.py
vnpy/trader/object.py
vnpy/trader/ui/widget.py

[Add]min_volume for ContractData

---

vnpy/gateway/okexf/__init__.py
vnpy/gateway/okexf/okexf_gateway.py

1. 对qqqlyx的OKEXFuture_gateway进行若干修复

[Add]Okex期货接口

---

tests/trader/run.py
vnpy/api/websocket/websocket_client.py
vnpy/app/cta_backtester/engine.py
vnpy/app/cta_backtester/ui/widget.py
vnpy/gateway/oes/oes_td.py
vnpy/gateway/okexf/okexf_gateway.py
vnpy/trader/constant.py

More exchange support

---

vnpy/gateway/ctp/ctp_gateway.py

修复AppID key错误

---

docs/cta_backtester.md

[Add] cta_backtester.md

---

docs/cta_backtester.md

[Mod] cta_backtester.md

---

docs/index.md

[Mod] index.md

---

docs/csv_loader.md
docs/cta_backtester.md
docs/cta_strategy.md
docs/index.md
docs/quickstart.md

1. 修改文档格式，兼容index.md
2. 补全cta_strategy文档内容

[Mod]修改说明文档

---

vnpy/app/cta_strategy/converter.py
vnpy/gateway/bitfinex/bitfinex_gateway.py
vnpy/gateway/bitmex/bitmex_gateway.py
vnpy/gateway/ctp/ctp_gateway.py
vnpy/gateway/femas/femas_gateway.py
vnpy/gateway/futu/futu_gateway.py
vnpy/gateway/huobi/huobi_gateway.py
vnpy/gateway/ib/ib_gateway.py
vnpy/gateway/oes/oes_gateway.py
vnpy/gateway/okex/okex_gateway.py
vnpy/gateway/okexf/okexf_gateway.py
vnpy/gateway/onetoken/onetoken_gateway.py
vnpy/gateway/tiger/tiger_gateway.py
vnpy/gateway/xtp/xtp_gateway.py
vnpy/trader/engine.py
vnpy/trader/gateway.py
vnpy/trader/rqdata.py
vnpy/trader/ui/widget.py

Gateway exchange

---

docs/gateway.md

[Add] gateway.md

---

tests/trader/run.py
vnpy/gateway/hbdm/__init__.py
vnpy/gateway/hbdm/hbdm_gateway.py

[Add]huobi derivatives gateway

---

vnpy/trader/ui/mainwindow.py
vnpy/trader/ui/widget.py

[Add]global setting editor

---

vnpy/trader/utility.py

[Add]support hour bar generation

---

vnpy/gateway/okexf/okexf_gateway.py

[Fix] Okexf_gateway

---

vnpy/api/rest/rest_client.py
vnpy/app/cta_backtester/engine.py
vnpy/app/cta_backtester/ui/widget.py
vnpy/app/cta_strategy/engine.py
vnpy/gateway/bitmex/bitmex_gateway.py
vnpy/trader/engine.py
vnpy/trader/gateway.py
vnpy/trader/object.py
vnpy/trader/rqdata.py

Query history

---

vnpy/app/cta_strategy/backtesting.py

1) 移除math库，种群数量默认100，迭代次数默认30。（用户可以自己调整）
2）增加基于遗传算法的全局参数生成器：generate_setting_ga。其格式为[[(key, value), (key,value)] , [(key, value), (key,value)] ]。（穷举算法的全局参数生成器为[{key:value, key:value}, {key:value, key:value}]）
3) 简化随机生成参数函数generate_parameter
4）新增遗传算法变异函数 mutate_individual
5) 修改函数拼写错误 _ga_optimize
6) 简化评估函数_ga_optimize的setting字典合成

[Mod] backtesting

---

setup.py
vnpy/app/cta_backtester/ui/widget.py
vnpy/gateway/hbdm/hbdm_gateway.py
vnpy/trader/engine.py
vnpy/trader/gateway.py

Batch trade

---

docs/datarecoder.md

[Add] datarecoder

---

docs/gateway.md

[Mod] gateway.md

---

README.md

[Del] duplicate info

---

docs/datarecoder.md
docs/index.md

- 在index目录增加datarecorder
- datarecorder.md增加停止记录和移除记录相关操作

[Add] Index update datarecorder

---

README.md

[Mod] update README.md

---

vnpy/app/algo_trading/algos/best_limit_algo.py
vnpy/app/algo_trading/algos/stop_algo.py
vnpy/app/algo_trading/engine.py

1. 增加stop_algo
2. 增加best_limit_algo
3.在engine中导入新增的算法

[Add]stop_algo; best_limit_algo 

---

vnpy/trader/utility.py

json写入支持中文字符

---

vnpy/app/algo_trading/algos/grid_algo.py
vnpy/app/algo_trading/engine.py

[Add]Grid algo 

---

vnpy/app/risk_manager/engine.py

[Add] Risk Manager engine

---

vnpy/app/cta_backtester/engine.py
vnpy/app/cta_backtester/ui/widget.py
vnpy/app/cta_strategy/backtesting.py
vnpy/trader/ui/widget.py

Backtester result

---

vnpy/app/algo_trading/ui/widget.py

[Add] start atrading algos from csv file

---

vnpy/app/algo_trading/algos/dma_algo.py
vnpy/app/algo_trading/algos/stop_algo.py
vnpy/app/algo_trading/engine.py

1. 增加DMA算法
2. 修复Stop Algo中direction=short，却发多单的bug

[Add] DMA algo 

---

vnpy/gateway/oes/oes_gateway.py
vnpy/gateway/oes/oes_td.py

[Add] OesGateway: Added option to set customize IP and MAC 
[Fix] fixed: OesGateway cann't connect to ord channel

[Fix] fixed: OesGateway cann't connect to ord channel

---

vnpy/app/algo_trading/algos/arbitrage_algo.py
vnpy/app/algo_trading/engine.py

[Add] Arb algo

---

vnpy/gateway/tiger/tiger_gateway.py

1. 基于最新的tiger python sdk里面提供的OrderStatus, 移除PUSH_STATUS_TIGER2VT字典
2. 增加多账号委托推送字典维护

[Update] tiger_gateway.py

---

docs/gateway.md

[Update] gateway.md

---

docs/install.md

[Update] install.md

---

docs/algo_trader.md

[Mod] algo_trader.md

---

docs/risk_manager.md

[Add] risk_manager.md

---

vnpy/app/cta_strategy/engine.py

ctaengine价格取整到最小价格变动

---

docs/cta_strategy.md

[Add] 投资组合使用文档

---

vnpy/app/cta_strategy/engine.py

修正StopOrder vt_orderids

---

docs/cta_strategy.md

【Add】增加cta引擎中的锁仓相关文档

---

vnpy/gateway/bitmex/bitmex_gateway.py

[Mod] bitmex_gateway增加持仓推送过滤

---

vnpy/app/cta_strategy/backtesting.py

1. 回测引擎增加日期过滤，若起始日期》=结束日期，输出提示信息，并且返回

[Mod] 回测引擎增加日期过滤

---

README.md

[Mod]update download link of vnstudio

---

README.md

[Mod] update vnstudio 2.0.4 download link

---

vnpy/trader/database/database_sql.py

1. 修复to_bar函数缺失open_interest字段

[Mod] 修复database_sql缺失字段

---

vnpy/gateway/binance/binance_gateway.py

1. 合约的price_tick和min_volume改成float

[Mod] binance_gateway

---

vnpy/gateway/onetoken/onetoken_gateway.py

更新one_token合约交易所代码

---

vnpy/api/rest/rest_client.py

1. rest_client的data参数增加参数增加其他格式支持

[Add] rest_client的data参数增加其他格式支持

---

vnpy/api/rest/rest_client.py
vnpy/gateway/alpaca/__init__.py
vnpy/gateway/alpaca/alpaca_gateway.py

[add] add alpaca gateway to vnpy

---

vnpy/app/cta_strategy/backtesting.py

1. 回测模块，修复加载历史数据的bug(截止日期赋值不准确)

修复加载历史数据的bug

---

vnpy/gateway/onetoken/onetoken_gateway.py

Fix onetoken order and trade

---

vnpy/app/cta_strategy/strategies/king_keltner_strategy.py

1. fix bug that can not cancel order

[Update] king_keltner_strategy.py

---

vnpy/app/script_trader/ui/widget.py

[Add] clear_button to clear log monitor

---

.github/SUPPORT.md

去除SUPPORT文件项目论坛后链接的多余空格

---

docs/gateway.md
vnpy/trader/engine.py

修正 MainEngine 中 app_class, gateway_class 的 type hint
Stack Overflow 相关讨论 https://stackoverflow.com/questions/44664040/type-hints-with-user-defined-classes
无

修正 MainEngine 中 app_class, gateway_class 的 type hint

---

examples/CtaBacktesting/runBacktesting.py
examples/CtaBacktesting/runOptimization.py
vnpy/trader/app/ctaStrategy/ctaBacktesting.py

1. 原始代码没有启动数据缓存服务客户端，导致后面的回测无法使用数据缓存服务，应增加行：engine.initHdsClient()
2. hds.stop() 和raw_input()的前后问题，raw_input()应该在前面，否则数据服务器启动后会立即关闭
3. runOptimization.py部分，后面的计算是基于日统计的，日统计中用的是totalNetPnl，没有capital,这里会导致结果为0，应改为 'totalNetPnl'后计算才正常。
Close #

V1.9.2 lts

---

docs/gateway.md

update gateway md 723

---

docs/script_trader.md
vnpy/app/script_trader/engine.py

script trader md &

---

docs/script_trader.md

script_trader 2.0 md

---

docs/cta_strategy.md

[Update] cta_strategy.md

---

docs/csv_loader.md

Update Csv loader

---

vnpy/app/cta_strategy/engine.py

修复本地停止单返回数据错误

---

docs/data_recoder.md

[Update] data_recoder.md

---

docs/cta_backtester.md

1. classify download data historical: RQData, IB, BITMEX
2. add introduction of bar_line chart

[Update] cta_backtester.md

---

docs/script_trader.md

1. configuracion and mejoracion

[Update] script_trader.md

---

docs/rpc_service.md

[Update] rpc_service.md

---

docs/quickstart.md

update quickstart md 86

---

vnpy/app/cta_strategy/engine.py

Add pyd strategy support

---

vnpy/app/rpc_service/engine.py
vnpy/gateway/rpc/rpc_gateway.py
vnpy/rpc/__init__.py

[Add] RpcClient: Added send lock.
[Add] RcpClient: Added Heartbeat package

[Add] RpcClient: Added send lock.

---

vnpy/api/asyncio/async_executor.py
vnpy/api/rest/rest_client.py
vnpy/api/websocket/websocket_client.py

[Mod] RestClient & WebsocketClient: start & stop asyncio automatically
[Mod] Optimized performance of async_executor
[Mod] Optimized stop() and join()

[Mod] RestClient & WebsocketClient: start & stop asyncio automatically

---

vnpy/api/rest/rest_client.py

[Mod] RestClient: use shared thread pool.

[Mod] RestClient: use shared thread pool.

---

vnpy/gateway/okexs/__init__.py
vnpy/gateway/okexs/okexs_gateway.py

[Add] Okex Swap API.

---

.circleci/config.yml
setup.py

[Add] .circleci/config.yml
[Add] new environment variable that can effect setup.py: VNPY_BUILD_PARALLEL=no

[Add] .circleci/config.yml

---

vnpy/gateway/coinbase/__init__.py
vnpy/gateway/coinbase/coinbase_gateway.py

1. 新增coinbase接口，但是还缺少一个定时轮询order的功能，其余正常
Close #

coinbase_gateway

---

vnpy/app/cta_strategy/backtesting.py

1. Add backtesting mode for crypto futures

Add backtesting mode for crypto futures

---

vnpy/app/spread_trading/ui/widget.py

[Fix] typo of vt_symbol

---

vnpy/api/rest/rest_client.py
vnpy/api/websocket/websocket_client.py
vnpy/trader/utility.py

[Add] logger for RestClient & WebsocketClient

[Add] logger for RestClient & WebsocketClient

---

vnpy/app/cta_strategy/engine.py

[Mod] change thread worker no

---

examples/data_analysis/data_analysis.ipynb
examples/data_analysis/data_analysis.py

[Add] Data analysis

---

vnpy/app/cta_strategy/backtesting.py

1. add a new index for backtesting result

[Add] max drawdown duration index

---

vnpy/trader/utility.py

[Add] more index from talib

---

vnpy/gateway/bybit/bybit_gateway.py

Revert "[Fix] query_history"

---

vnpy/gateway/bybit/bybit_gateway.py

Dev portfolio manager

---

README.md

[Mod] update download link

---

vnpy/trader/utility.py

[Add] more talib support

---

vnpy/gateway/tiger/tiger_gateway.py
vnpy/trader/constant.py

1.  [VNPY]添加期货交易所
2. [tiger_gateway]增加期货合约的查询交易、增加期货订单与持仓的查询
3. [tiger_gateway]增加本地订单号模式的异常处理
4. [tiger_gateway]完善标准、模拟、环球账户的支持
5. [tiger_gateway]在 tigeropen 层面，使用 identifier 做为资产的唯一标识
6. [tiger_gateway]改进 gateway 层面的tick推送策略，对于只产生了时间戳的tick事件，不再推送。
7. [tiger_gateway]使用最高价与最低价兼容本地止损单的处理逻辑
8. [tiger_gateway]处理了过去订阅多个账户信息没有退订，导致推送多个账户信息的问题
Close #

Dev tiger futures

---

vnpy/api/websocket/websocket_client.py

Unify Code Style

---

vnpy/gateway/ib/ib_gateway.py
vnpy/trader/object.py

【Mod】 add typing info to vnpy.trader.object 

---

vnpy/gateway/ib/ib_gateway.py
vnpy/trader/gateway.py

【Mod】Add typing info to vnpy.trader.gateway

---

vnpy/gateway/ib/ib_gateway.py

1. 登陆后，立刻订阅json里面缓存的合约
2. 新增合约会同时缓存到json字典内
3. 最订阅的品种做特殊处理，无需输入conin：
- 外汇： CBP/USD   (symbol/curreny)
- 期货：IF-2001@CHN (symbol-expire@currency)
-  期权：IO-200101-C-4000@CHN (symbol-expire-right-strike@currency)
其他标的，如债券，etf，股票，统一为symbol#type@currency，如AAPL#STK@USD
4 订阅合约后，底层缓存conId，输入上面的合约格式即可发单

IB接口合约订阅改进

---

vnpy/trader/setting.py

[Mod] add type info to vnpy.trader.setting

---

vnpy/gateway/ib/ib_gateway.py
vnpy/trader/engine.py

【Mod】add typing  info to vnpy.trader.engine

---

vnpy/trader/engine.py

[Mod] add typing info to  vnpy.trader.engine

---

vnpy/trader/gateway.py

[Mod] add type info to vnpy.trader.gateway

---

vnpy/rpc/__init__.py

[Mod] add typing info to vnpy.rpc

---

vnpy/rpc/__init__.py

[Fix] add type info to vnpy.rpc

---

vnpy/event/engine.py

[Mod] add typing info to vnpy.evnet,engine

---

vnpy/trader/rqdata.py

[Mod] add typing info to vnpy.trader.rqdata

---

vnpy/trader/app.py

[Mod] add typing info to vnpy.trader.app

---

vnpy/trader/converter.py

[Mod] add typing info to vnpy.trader.converter

---

vnpy/trader/ui/__init__.py
vnpy/trader/ui/editor.py
vnpy/trader/ui/mainwindow.py
vnpy/trader/ui/widget.py

[Mod] Add typing info to vnpy.trader.ui

---

vnpy/gateway/uft/uft_gateway.py

[Mod] add uft_gateway to vnpy.gateway.uft

---

vnpy/app/csv_loader/engine.py

保存CSV数据前移除null值

---

README.md

1. README “其他内容"下各条目超链接从 doc/ 路径更新到 .github/ 路径。
Close # N/A

更新README文档中的链接

---

README.md

[Mod] update vnstudio download link

---

vnpy/gateway/okexf/okexf_gateway.py

修复OKEX期货订阅账户错误

---

docs/script_trader.md

1. about buy funciont, price and volume should be type of int, not str

[Fix] fix bug en vnpy.doc.script_trader.md

---

examples/vn_trader/run.py
vnpy/gateway/binancef/__init__.py
vnpy/gateway/binancef/binancef_gateway.py

[Mod] add vnpy.gateway.binancef_gateway

---

vnpy/gateway/okexo/__init__.py
vnpy/gateway/okexo/okexo_gateway.py

[Mod] add vnpy.gateway.okexo_gateway

---

vnpy/gateway/onetoken/onetoken_gateway.py

修复1token行情重连收不到行情的问题

---

examples/cta_tui/run.py
requirements.txt
setup.py

1. Terminal UI 界面
2. 在GUI和完全没有界面中间取一个平衡
3. 适合在无法安装GUI的低性能服务器中，又能得到一部分交易界面的信息
Close #

[Mod] 高性能Terminal UI 界面

---

examples/cta_tui/run.py

1. 修复Terminal UI 中文字符显示问题 
Close #

[fix] 修复Terminal UI 中文字符显示问题 

---

docs/install.md

1. 缺少转义符，路径显示错误
2. 
3.
Close #

缺少转义符，路径显示错误

---

vnpy/gateway/binancef/binancef_gateway.py

修复binancef一些BUG

---

vnpy/gateway/okex/okex_gateway.py

okex接口增加断线重新订阅

---

vnpy/gateway/hsoption/hsoption_gateway.py

[Mod] Fix bug with no data and write_log something error

---

vnpy/gateway/kaisa/__init__.py
vnpy/gateway/kaisa/kaisa_gateway.py

[Mod] add vnpy.gateway.kaisa

---

vnpy/gateway/kaisa/kaisa_gateway.py

[Mod] mod encrypt password

---

vnpy/gateway/tora/md.py
vnpy/gateway/tora/tora_gateway.py

华鑫奇点行情API需要执行登录操作

---

vnpy/app/cta_strategy/engine.py

增加linux cython策略的支持

---

vnpy/gateway/mini/mini_gateway.py

[Mod] add datetime ajust to vnpy.gateway.mini

---

vnpy/gateway/minitest/minitest_gateway.py

[Mod] add datetime ajust to vnpy.gateway.mini test 

---

vnpy/gateway/rohon/rohon_gateway.py

[Mod] add datetime ajust to vnpy.gateway.rohon

---

vnpy/gateway/sgit/sgit_gateway.py

[Mod] add datetime ajust to vnpy.gateway.sgit

---

vnpy/gateway/sopt/sopt_gateway.py

[Mod] add datetime ajust to vnpy.gateway.sopt

---

vnpy/gateway/uft/uft_gateway.py

[Mod] add datetime ajust to vnpy.gateway.uft

---

setup.py

[mod] add xtp support in ubuntu

---

vnpy/gateway/sopttest/sopttest_gateway.py

[Mod] add datetime ajust to vnpy.gateway.sopttest

---

vnpy/gateway/huobi/huobi_gateway.py

1. trade websocket 支持ws/v2（新增签名函数，账号资金推送）
2. 移除rest端 轮询函数query account balance
3. 账号资金推送规则：websocket登录都推送全量信息，之后是push update
4. 增加静态类型标注

[Mod] update huobi gateway support websocket v2

---

vnpy/gateway/bybit/bybit_gateway.py

[Mod] upadate bybit gateway to support usdt stype

---

vnpy/gateway/bybit/bybit_gateway.py
vnpy/gateway/huobi/huobi_gateway.py

Dev bybit usdt

---

vnpy/gateway/huobis/__init__.py
vnpy/gateway/huobis/huobis_gateway.py

[Mod] add huobis gateway

---

vnpy/gateway/onetoken/onetoken_gateway.py

修复1token datetime转化错误

---

requirements.txt

[Mod] add PyQt5/pyqtgraph version number

---

vnpy/app/portfolio_strategy/engine.py

it will cause the problem that can't not update the pos

[fix] fixed update pos problem

---

vnpy/app/cta_strategy/engine.py

make it more gentility

---

vnpy/app/portfolio_strategy/engine.py

portfolio log gateway name is wrong

---

vnpy/gateway/ib/ib_gateway.py

1. fix minnor typo in ib_gateway
2. 
3.
Close #

[fix] fix minnor typo

---

vnpy/gateway/ib/ib_gateway.py

1. fix the crash if order fulfilled by unexpected exchange, like ISLAND or IBKRATS

[Fix] fix the crash if order fulfilled by unexpected exchange

---

examples/genus_client/log.txt
examples/genus_client/run_child.py

[Mod] add accepotr channel log and py file

---

.github/workflows/pythonapp.yml

[Mod] install quickfix in github action script

---

vnpy/api/oes/vnoes/vnoesmd/01_mds_async_tcp_sample.c
vnpy/api/oes/vnoes/vnoesmd/mds_client.c
vnpy/api/oes/vnoes/vnoesmd/vnoesmd.cpp
vnpy/api/oes/vnoes/vnoesmd/vnoesmd.h
vnpy/api/oes/vnoes/vnoesmd/vnoesmd.vcxproj
vnpy/api/oes/vnoes/vnoesmd/vnoesmd.vcxproj.filters

[Mod] merge "mds_client_sample" logic in vnoesmd.cpp

---

vnpy/gateway/binances/binances_gateway.py

[Mod] support Inverse contract in vnpy.gateway.binances

---

vnpy/trader/utility.py

1. fix a warning in Pycharm
2. 
3.
Close #

fix a warning in Pycharm

---

vnpy/gateway/huobio/__init__.py
vnpy/gateway/huobio/huobio_gateway.py

[Add] huobi option gateway

---

requirements.txt
vnpy/app/option_master/time.py

1. 从trading-calendars自动获取节假日，用于期权定价
2. 
3.
Close #

auto holiday

---

docs/index.rst

[Mod] update doc index

---

vnpy/app/cta_strategy/backtesting.py
vnpy/app/portfolio_strategy/backtesting.py

[Mod] add risk free in calculating sharpe ratio

---

vnpy/app/spread_trading/base.py
vnpy/app/spread_trading/engine.py
vnpy/app/spread_trading/ui/widget.py

Dev advanced spread

---

vnpy/app/cta_strategy/backtesting.py

fix a typo

---

vnpy/gateway/futu/futu_gateway.py

create 3 different trade context for US,HK and CN at the same time.
add query history bar function in futu gateway
add emualation support for futu gateway
Signed-off-by: Xiaowei Wang <wangxiaowei_cloud@outlook.com>
1. 
2. 
3.
Close #

add futu support

---

requirements.txt
vnpy/app/portfolio_manager/ui/widget.py

[Mod] import from QtWidgets instead of QtGui

---

vnpy/api/rest/rest_client.py
vnpy/gateway/huobil/__init__.py
vnpy/gateway/huobil/huobil_gateway.py

支持 Huobi 的 USDT 正向永续合约交易
Fix #2786

支持 Huobi 的 USDT 正向永续合约交易

---

docs/market_radar.md

[Mod]Update market_radar.md

---

docs/data_recorder.md
docs/portfolio_manager.md
docs/risk_manager.md

1. 增加了PortfolioManager模块的解释说明
2. 图片2-4由于过了交易时间还没来得及复现（暂时用的带有微信水印的），明天会替换掉
Close #

[Mod]Update portfolio_manager.md

---

vnpy/database/mysql/mysql_database.py

[Fix] remove interval field from dict when saving tick data

---

vnpy/app/market_radar/ui/widget.py

[Mod] change ui widget size

---

docs/chart_wizard.md

1. 修改了docs/chart_wizard.md文件
2. 
3.
Close #

[Mod]update chart_wizard.md

---

docs/spread_trading.md

1. 修改了spread_trading.md文件
2. 
3.
Close #

[Mod]update spread_trading.md

---

docs/quickstart.md

â-m[Mod]update quickstart.md

---

docs/install.md

1. 修改了install.md文件
2. 
3.
Close #

[Mod]update install.md

---

docs/database.md

1. 修改了database.md文件
2. 
3.
Close #

Dev docs  -  [Mod]update database.md

---

vnpy/app/cta_strategy/ui/widget.py
vnpy/trader/ui/mainwindow.py
vnpy/trader/ui/widget.py

1. 添加新日志 Widget, 继承自 QTextEdit.
Close #2865

Add new log widget using QTextEdit.

---

docs/rpc_service.md

1. 修改了rpc_service.md文件
2. 
3.
Close #

[Mod]update rpc_service.md

---

vnpy/gateway/ib/ib_gateway.py

1.  修复当使用 IB 加载日度、周度数据时由于格式错误导致的报错
2. 
3.
Close #

Fix IB history daily data format error

---

requirements.txt

[Mod] lock tzlocal version to 2.0.0

---

vnpy/gateway/gateios/gateios_gateway.py

修复gateios接口查询委托单orderid自增的BUG

---

docs/portfolio_strategy.md

修复示例策略写错的代码

---

install.sh

使用多线程编译TALib会导致一系列问题。使用单线程会防止编译失败
https://github.com/mrjbq7/ta-lib#dependencies
1. 使用单线程编译 talib
Close #

Force talib compiles in one thread.

---

README.md

[Mod] update qrcode

---

examples/spread_backtesting/backtesting.ipynb

回测脚本添加compile_formula注释

---

docs/excel_rtd.md

excel_rtd文档更新

---

README.md

[Mod] update readme

---

README.md

[Fix] typo

---

docs/ubuntu_install.md
install.sh

1. 解决locale-gen zh_CN.GB18030命令无效问题
2. 添加换源可选项

[Mod] 更新linux安装脚本

---

vnpy/rpc/client.py
vnpy/rpc/common.py
vnpy/rpc/server.py

[Mod] type declaration - vnpy.rpc

---

vnpy/event/engine.py

[Add] type declaration - vnpy.event

---

requirements.txt

[Del] 移除tzlocal版本限制

---

vnpy/chart/axis.py
vnpy/chart/item.py
vnpy/chart/manager.py
vnpy/chart/widget.py

[Add] type declaration - vnpy.chart

---

vnpy/trader/ui/mainwindow.py
vnpy/trader/ui/qt.py
vnpy/trader/ui/widget.py

 [Mod] type declaration - vnpy.trader.ui

---

vnpy/trader/app.py
vnpy/trader/converter.py
vnpy/trader/database.py
vnpy/trader/datafeed.py
vnpy/trader/engine.py
vnpy/trader/gateway.py
vnpy/trader/object.py
vnpy/trader/optimize.py
vnpy/trader/setting.py
vnpy/trader/utility.py

[Add] type declaration - vnpy.trader

---

setup.cfg

[Mod] update setup.cfg

---

docs/veighna_station.md
docs/web_trader.md

1. 修改了文档中的两处笔误
2. 删除了文档中的两处结尾空格
无

[Doc] Fix a few typos in the doc

---

requirements.txt

[Mod] set numpy version to 1.21.5 to ensure Python 3.7 compatability

---

requirements.txt
vnpy/trader/utility.py

[Add] backports.zoneinfo

---

README.md

1. 修正中文版readme.md中拼写错误 "bufix" -> "bugfix"
2.

typo: correct syntax error in readme.md

---

vnpy/trader/database.py
vnpy/trader/ui/widget.py

[Mod] replace pytz

---

vnpy/trader/engine.py

type(engine.py): fix typo

---

docs/spread_trading.md

type(spread_trading.md): fix demo code in doc

---

docs/portfolio_strategy.md

[Add] update portfolio_strategy.md

---

vnpy/trader/object.py

1. vnpy/trader/object.py中定义的PositionData注释下“Positon data is used for tracking each individual position holding.”中Position拼写错误。本次修改内容为Positon改为Position。
Close #

feat: fixed word spelling error: Positon -> Position

---

vnpy/trader/ui/qt.py

[Del] 删除用不到的代码

---

README.md

[Mod] update badages in readme.md

---

docs/script_trader.md

[Mod] 更新script_trader.md

---

docs/mac_install.md

[Add] 增加mac安装文档

---

vnpy/trader/datafeed.py

[Mod] 修改datafeed加载方式

---

vnpy/trader/utility.py

[Add] 增加日线合成支持

---

docs/pycharm.md
docs/spread_trading.md
docs/veighna_trader.md
examples/veighna_trader/run.py

[Mod] 调整文档

---

MANIFEST.in
docs/community/app/i18n.md
docs/community/app/index.rst
vnpy/locale/__init__.py
vnpy/locale/en/LC_MESSAGES/vnpy.po
vnpy/locale/vnpy.pot
vnpy/trader/constant.py
vnpy/trader/database.py
vnpy/trader/datafeed.py
vnpy/trader/engine.py
vnpy/trader/optimize.py
vnpy/trader/setting.py
vnpy/trader/ui/mainwindow.py
vnpy/trader/ui/qt.py
vnpy/trader/ui/widget.py
vnpy/trader/utility.py

@vnpy Firstly - awesome project. Thanks for releasing, great work
1. A proposal for an internationalization (i18n) framework 
2. includes English language translation files
3. includes doc page
This is a proposal, a starting point for a conversation if you like. Its left in *draft* status, please suggest any improvements
Close #

Internationalization (i18n)

---

vnpy/trader/utility.py

[Mod] 兼容"HHI.HK-HKD-FUT.HKFE"

---

vnpy/rpc/client.py

[Fix] issue 3492

---

requirements.txt

[Mod] requirements.txt

---

vnpy/trader/constant.py
vnpy/trader/locale/en/LC_MESSAGES/vnpy.po
vnpy/trader/locale/vnpy.pot

[Mod] 增加cfd和swap支持

---

install.bat

[Mod] 统一Windows和Linux脚本的入参

---

docs/elite/extension/elite_dingtalk.md
docs/elite/extension/elite_feishu.md

[Add] elite_feishu.md

---

docs/community/info/vscode.md

[Add] vscode.md

---

docs/elite/strategy/elite_datamanager.md

[Mod] 更新文档

---

vnpy/trader/constant.py

[Mod] constant

---

docs/elite/strategy/elite_riskmanager.md

[Add] elite_riskmanager.md

---

vnpy/trader/ui/widget.py

1. 问题: 各种monitor会出先排序错误.
2. 解决: 给`BaseCell` 添加 `__lt__` 方法.
3. 参考: https://stackoverflow.com/a/75422673/19868974
Close #

[Mod] 增强table排序

---

vnpy/trader/app.py

Typo fix: Absstract -> Abstract
1.  Typo fix
Close #

Fix typo in app.py

---

vnpy/trader/optimize.py

[Mod] run_ga_optimization

---

docs/elite/strategy/elite_ctastrategy.md

[Mod] 更新elite_ctastrategy文档
